#!/usr/bin/env bash

APPDIR="$(dirname -- "$(readlink -f -- "${0}")" )"

LIBDIR="$APPDIR"/lib
for LIB in \
    "$LIBDIR"/*.jar \
    ;
do
    CLASSPATH="${CLASSPATH}:${LIB}"
done
export CLASSPATH

JAVA=java
if [ -x "$APPDIR/java/bin/java" ]; then
  JAVA=$APPDIR/java/bin/java
fi

# Collect options to java in an array, to properly handle whitespace in options
JAVA_OPTIONS=("-DAPP_DIR=$APPDIR" "-Dcom.apple.macos.useScreenMenuBar=true" "-XstartOnFirstThread")

"$JAVA" "${JAVA_OPTIONS[@]}" com.maccasoft.propeller.SpinTools "$@"
