/*
 * Copyright (c) 2021 Marco Maccaferri and others.
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */

package com.maccasoft.propeller.spin;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.maccasoft.propeller.expressions.Expression;
import com.maccasoft.propeller.spin.instructions.*;
import com.maccasoft.propeller.spin.instructions.Byte;
import com.maccasoft.propeller.spin.instructions.Long;

public abstract class Spin2PAsmInstructionFactory extends Expression {

    static Map<String, Spin2PAsmInstructionFactory> symbols = new HashMap<String, Spin2PAsmInstructionFactory>();
    static {
        symbols.put("asmclk", new AsmClk());

        symbols.put("org", new Org());
        symbols.put("orgh", new Orgh());
        symbols.put("res", new Res());

        // Instructions
        symbols.put("nop", new Nop());
        symbols.put("ror", new Ror());
        symbols.put("rol", new Rol());
        symbols.put("shr", new Shr());
        symbols.put("shl", new Shl());
        symbols.put("rcr", new Rcr());
        symbols.put("rcl", new Rcl());
        symbols.put("sar", new Sar());
        symbols.put("sal", new Sal());
        symbols.put("add", new Add());
        symbols.put("addx", new Addx());
        symbols.put("adds", new Adds());
        symbols.put("addsx", new Addsx());
        symbols.put("sub", new Sub());
        symbols.put("subx", new Subx());
        symbols.put("subs", new Subs());
        symbols.put("subsx", new Subsx());
        symbols.put("cmp", new Cmp());
        symbols.put("cmpx", new Cmpx());
        symbols.put("cmps", new Cmps());
        symbols.put("cmpsx", new Cmpsx());
        symbols.put("cmpr", new Cmpr());
        symbols.put("cmpm", new Cmpm());
        symbols.put("subr", new Subr());
        symbols.put("cmpsub", new Cmpsub());
        symbols.put("fge", new Fge());
        symbols.put("fle", new Fle());
        symbols.put("fges", new Fges());
        symbols.put("fles", new Fles());
        symbols.put("sumc", new Sumc());
        symbols.put("sumnc", new Sumnc());
        symbols.put("sumz", new Sumz());
        symbols.put("sumnz", new Sumnz());
        symbols.put("testb", new Testb());
        symbols.put("testbn", new Testbn());
        symbols.put("bitl", new Bitl());
        symbols.put("bith", new Bith());
        symbols.put("bitc", new Bitc());
        symbols.put("bitnc", new Bitnc());
        symbols.put("bitz", new Bitz());
        symbols.put("bitnz", new Bitnz());
        symbols.put("bitrnd", new Bitrnd());
        symbols.put("bitnot", new Bitnot());
        symbols.put("and", new And());
        symbols.put("andn", new Andn());
        symbols.put("or", new Or());
        symbols.put("xor", new Xor());
        symbols.put("muxc", new Muxc());
        symbols.put("muxnc", new Muxnc());
        symbols.put("muxz", new Muxz());
        symbols.put("muxnz", new Muxnz());
        symbols.put("mov", new Mov());
        symbols.put("not", new Not());
        symbols.put("abs", new Abs());
        symbols.put("neg", new Neg());
        symbols.put("negc", new Negc());
        symbols.put("negnc", new Negnc());
        symbols.put("negz", new Negz());
        symbols.put("negnz", new Negnz());
        symbols.put("incmod", new Incmod());
        symbols.put("decmod", new Decmod());
        symbols.put("zerox", new Zerox());
        symbols.put("signx", new Signx());
        symbols.put("encod", new Encod());
        symbols.put("ones", new Ones());
        symbols.put("test", new Test());
        symbols.put("testn", new Testn());
        symbols.put("setnib", new Setnib());
        symbols.put("getnib", new Getnib());
        symbols.put("rolnib", new Rolnib());
        symbols.put("setbyte", new Setbyte());
        symbols.put("getbyte", new Getbyte());
        symbols.put("rolbyte", new Rolbyte());
        symbols.put("setword", new Setword());
        symbols.put("getword", new Getword());
        symbols.put("rolword", new Rolword());
        symbols.put("altsn", new Altsn());
        symbols.put("altgn", new Altgn());
        symbols.put("altsb", new Altsb());
        symbols.put("altgb", new Altgb());
        symbols.put("altsw", new Altsw());
        symbols.put("altgw", new Altgw());
        symbols.put("altr", new Altr());
        symbols.put("altd", new Altd());
        symbols.put("alts", new Alts());
        symbols.put("altb", new Altb());
        symbols.put("alti", new Alti());
        symbols.put("setr", new Setr());
        symbols.put("setd", new Setd());
        symbols.put("sets", new Sets());
        symbols.put("decod", new Decod());
        symbols.put("bmask", new Bmask());
        symbols.put("crcbit", new Crcbit());
        symbols.put("crcnib", new Crcnib());
        symbols.put("muxnits", new Muxnits());
        symbols.put("muxnibs", new Muxnibs());
        symbols.put("muxq", new Muxq());
        symbols.put("movbyts", new Movbyts());
        symbols.put("mul", new Mul());
        symbols.put("muls", new Muls());
        symbols.put("sca", new Sca());
        symbols.put("scas", new Scas());
        symbols.put("addpix", new Addpix());
        symbols.put("mulpix", new Mulpix());
        symbols.put("blnpix", new Blnpix());
        symbols.put("mixpix", new Mixpix());
        symbols.put("addct1", new Addct1());
        symbols.put("addct2", new Addct2());
        symbols.put("addct3", new Addct3());
        symbols.put("wmlong", new Wmlong());
        symbols.put("rqpin", new Rqpin());
        symbols.put("rdpin", new Rdpin());
        symbols.put("rdlut", new Rdlut());
        symbols.put("rdbyte", new Rdbyte());
        symbols.put("rdword", new Rdword());
        symbols.put("rdlong", new Rdlong());
        symbols.put("popa", new Popa());
        symbols.put("popb", new Popb());
        symbols.put("calld", new Calld());
        symbols.put("resi3", new Resi3());
        symbols.put("resi2", new Resi2());
        symbols.put("resi1", new Resi1());
        symbols.put("resi0", new Resi0());
        symbols.put("reti3", new Reti3());
        symbols.put("reti2", new Reti2());
        symbols.put("reti1", new Reti1());
        symbols.put("reti0", new Reti0());
        symbols.put("callpa", new Callpa());
        symbols.put("callpb", new Callpb());
        symbols.put("djz", new Djz());
        symbols.put("djnz", new Djnz());
        symbols.put("djf", new Djf());
        symbols.put("djnf", new Djnf());
        symbols.put("ijz", new Ijz());
        symbols.put("ijnz", new Ijnz());
        symbols.put("tjz", new Tjz());
        symbols.put("tjnz", new Tjnz());
        symbols.put("tjf", new Tjf());
        symbols.put("tjnf", new Tjnf());
        symbols.put("tjs", new Tjs());
        symbols.put("tjns", new Tjns());
        symbols.put("tjv", new Tjv());
        symbols.put("jint", new Jint());
        symbols.put("jct1", new Jct1());
        symbols.put("jct2", new Jct2());
        symbols.put("jct3", new Jct3());
        symbols.put("jse1", new Jse1());
        symbols.put("jse2", new Jse2());
        symbols.put("jse3", new Jse3());
        symbols.put("jse4", new Jse4());
        symbols.put("jpat", new Jpat());
        symbols.put("jfbw", new Jfbw());
        symbols.put("jxmt", new Jxmt());
        symbols.put("jxfi", new Jxfi());
        symbols.put("jxro", new Jxro());
        symbols.put("jxrl", new Jxrl());
        symbols.put("jatn", new Jatn());
        symbols.put("jqmt", new Jqmt());
        symbols.put("jnint", new Jnint());
        symbols.put("jnct1", new Jnct1());
        symbols.put("jnct2", new Jnct2());
        symbols.put("jnct3", new Jnct3());
        symbols.put("jnse1", new Jnse1());
        symbols.put("jnse2", new Jnse2());
        symbols.put("jnse3", new Jnse3());
        symbols.put("jnse4", new Jnse4());
        symbols.put("jnpat", new Jnpat());
        symbols.put("jnfbw", new Jnfbw());
        symbols.put("jnxmt", new Jnxmt());
        symbols.put("jnxfi", new Jnxfi());
        symbols.put("jnxro", new Jnxro());
        symbols.put("jnxrl", new Jnxrl());
        symbols.put("jnatn", new Jnatn());
        symbols.put("jnqmt", new Jnqmt());
        symbols.put("setpat", new Setpat());
        symbols.put("akpin", new Akpin());
        symbols.put("wrpin", new Wrpin());
        symbols.put("wxpin", new Wxpin());
        symbols.put("wypin", new Wypin());
        symbols.put("wrlut", new Wrlut());
        symbols.put("wrbyte", new Wrbyte());
        symbols.put("wrword", new Wrword());
        symbols.put("wrlong", new Wrlong());
        symbols.put("pusha", new Pusha());
        symbols.put("pushb", new Pushb());
        symbols.put("rdfast", new Rdfast());
        symbols.put("wrfast", new Wrfast());
        symbols.put("fblock", new Fblock());
        symbols.put("xinit", new Xinit());
        symbols.put("xstop", new Xstop());
        symbols.put("xzero", new Xzero());
        symbols.put("xcont", new Xcont());
        symbols.put("rep", new Rep());
        symbols.put("coginit", new Coginit());
        symbols.put("qmul", new Qmul());
        symbols.put("qdiv", new Qdiv());
        symbols.put("qfrac", new Qfrac());
        symbols.put("qsqrt", new Qsqrt());
        symbols.put("qrotate", new Qrotate());
        symbols.put("qvector", new Qvector());
        symbols.put("hubset", new Hubset());
        symbols.put("cogid", new Cogid());
        symbols.put("cogstop", new Cogstop());
        symbols.put("locknew", new Locknew());
        symbols.put("lockret", new Lockret());
        symbols.put("locktry", new Locktry());
        symbols.put("lockrel", new Lockrel());
        symbols.put("qlog", new Qlog());
        symbols.put("qexp", new Qexp());
        symbols.put("rfbyte", new Rfbyte());
        symbols.put("rfword", new Rfword());
        symbols.put("rflong", new Rflong());
        symbols.put("rfvar", new Rfvar());
        symbols.put("rfvars", new Rfvars());
        symbols.put("wfbyte", new Wfbyte());
        symbols.put("wfword", new Wfword());
        symbols.put("wflong", new Wflong());
        symbols.put("getqx", new Getqx());
        symbols.put("getqy", new Getqy());
        symbols.put("getct", new Getct());
        symbols.put("getrnd", new Getrnd());
        symbols.put("setdacs", new Setdacs());
        symbols.put("setxfrq", new Setxfrq());
        symbols.put("getxacc", new Getxacc());
        symbols.put("waitx", new Waitx());
        symbols.put("setse1", new Setse1());
        symbols.put("setse2", new Setse2());
        symbols.put("setse3", new Setse3());
        symbols.put("setse4", new Setse4());
        symbols.put("pollint", new Pollint());
        symbols.put("pollct1", new Pollct1());
        symbols.put("pollct2", new Pollct2());
        symbols.put("pollct3", new Pollct3());
        symbols.put("pollse1", new Pollse1());
        symbols.put("pollse2", new Pollse2());
        symbols.put("pollse3", new Pollse3());
        symbols.put("pollse4", new Pollse4());
        symbols.put("pollpat", new Pollpat());
        symbols.put("pollfbw", new Pollfbw());
        symbols.put("pollxmt", new Pollxmt());
        symbols.put("pollxfi", new Pollxfi());
        symbols.put("pollxro", new Pollxro());
        symbols.put("pollxrl", new Pollxrl());
        symbols.put("pollatn", new Pollatn());
        symbols.put("pollqmt", new Pollqmt());
        symbols.put("waitint", new Waitint());
        symbols.put("waitct1", new Waitct1());
        symbols.put("waitct2", new Waitct2());
        symbols.put("waitct3", new Waitct3());
        symbols.put("waitse1", new Waitse1());
        symbols.put("waitse2", new Waitse2());
        symbols.put("waitse3", new Waitse3());
        symbols.put("waitse4", new Waitse4());
        symbols.put("waitpat", new Waitpat());
        symbols.put("waitfbw", new Waitfbw());
        symbols.put("waitxmt", new Waitxmt());
        symbols.put("waitxfi", new Waitxfi());
        symbols.put("waitxro", new Waitxro());
        symbols.put("waitxrl", new Waitxrl());
        symbols.put("waitatn", new Waitatn());
        symbols.put("allowi", new Allowi());
        symbols.put("stalli", new Stalli());
        symbols.put("trgint1", new Trgint1());
        symbols.put("trgint2", new Trgint2());
        symbols.put("trgint3", new Trgint3());
        symbols.put("nixint1", new Nixint1());
        symbols.put("nixint2", new Nixint2());
        symbols.put("nixint3", new Nixint3());
        symbols.put("setint1", new Setint1());
        symbols.put("setint2", new Setint2());
        symbols.put("setint3", new Setint3());
        symbols.put("setq", new Setq());
        symbols.put("setq2", new Setq2());
        symbols.put("push", new Push());
        symbols.put("pop", new Pop());
        symbols.put("jmp", new Jmp());
        symbols.put("call", new Call());
        symbols.put("ret", new Ret());
        symbols.put("calla", new Calla());
        symbols.put("reta", new Reta());
        symbols.put("callb", new Callb());
        symbols.put("retb", new Retb());
        symbols.put("jmprel", new Jmprel());
        symbols.put("skip", new Skip());
        symbols.put("skipf", new Skipf());
        symbols.put("execf", new Execf());
        symbols.put("getptr", new Getptr());
        symbols.put("getbrk", new Getbrk());
        symbols.put("cogbrk", new Cogbrk());
        symbols.put("brk", new Brk());
        symbols.put("setluts", new Setluts());
        symbols.put("setcy", new Setcy());
        symbols.put("setci", new Setci());
        symbols.put("setcq", new Setcq());
        symbols.put("setcfrq", new Setcfrq());
        symbols.put("setcmod", new Setcmod());
        symbols.put("setpiv", new Setpiv());
        symbols.put("setpix", new Setpix());
        symbols.put("cogatn", new Cogatn());
        symbols.put("testp", new Testp());
        symbols.put("testpn", new Testpn());
        symbols.put("dirl", new Dirl());
        symbols.put("dirh", new Dirh());
        symbols.put("dirc", new Dirc());
        symbols.put("dirnc", new Dirnc());
        symbols.put("dirz", new Dirz());
        symbols.put("dirnz", new Dirnz());
        symbols.put("dirrnd", new Dirrnd());
        symbols.put("dirnot", new Dirnot());
        symbols.put("outl", new Outl());
        symbols.put("outh", new Outh());
        symbols.put("outc", new Outc());
        symbols.put("outnc", new Outnc());
        symbols.put("outz", new Outz());
        symbols.put("outnz", new Outnz());
        symbols.put("outrnd", new Outrnd());
        symbols.put("outnot", new Outnot());
        symbols.put("fltl", new Fltl());
        symbols.put("flth", new Flth());
        symbols.put("fltc", new Fltc());
        symbols.put("fltnc", new Fltnc());
        symbols.put("fltz", new Fltz());
        symbols.put("fltnz", new Fltnz());
        symbols.put("fltrnd", new Fltrnd());
        symbols.put("fltnot", new Fltnot());
        symbols.put("drvl", new Drvl());
        symbols.put("drvh", new Drvh());
        symbols.put("drvc", new Drvc());
        symbols.put("drvnc", new Drvnc());
        symbols.put("drvz", new Drvz());
        symbols.put("drvnz", new Drvnz());
        symbols.put("drvrnd", new Drvrnd());
        symbols.put("drvnot", new Drvnot());
        symbols.put("splitb", new Splitb());
        symbols.put("mergeb", new Mergeb());
        symbols.put("splitw", new Splitw());
        symbols.put("mergew", new Mergew());
        symbols.put("seussf", new Seussf());
        symbols.put("seussr", new Seussr());
        symbols.put("rgbsqz", new Rgbsqz());
        symbols.put("rgbexp", new Rgbexp());
        symbols.put("xoro32", new Xoro32());
        symbols.put("rev", new Rev());
        symbols.put("rczr", new Rczr());
        symbols.put("rczl", new Rczl());
        symbols.put("wrc", new Wrc());
        symbols.put("wrnc", new Wrnc());
        symbols.put("wrz", new Wrz());
        symbols.put("wrnz", new Wrnz());
        symbols.put("modcz", new Modcz());
        symbols.put("modc", new Modc());
        symbols.put("modz", new Modz());
        symbols.put("setscp", new Setscp());
        symbols.put("getscp", new Getscp());
        symbols.put("loc", new Loc());
        symbols.put("augs", new Augs());
        symbols.put("augd", new Augd());

        // Directives
        symbols.put("long", new Long());
        symbols.put("word", new Word());
        symbols.put("byte", new Byte());
    }

    public static Spin2PAsmInstructionFactory get(String mnemonic) {
        return mnemonic != null ? symbols.get(mnemonic.toLowerCase()) : Empty.instance;
    }

    public Spin2PAsmInstructionFactory() {
    }

    public List<Spin2PAsmLine> expand(Spin2PAsmLine line) {
        return Collections.singletonList(line);
    }

    public abstract Spin2InstructionObject createObject(Spin2Context context, String condition, List<Spin2PAsmExpression> arguments, String effect);

}
