/*
 * Copyright (c) 2021 Marco Maccaferri and others.
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */

package com.maccasoft.propeller.spin;

import com.maccasoft.propeller.expressions.NumberLiteral;
import com.maccasoft.propeller.spin.instructions.*;

public class Spin2GlobalContext extends Spin2Context {

    public Spin2GlobalContext() {

        addSymbol("asmclk", new AsmClk());

        addSymbol("org", new Org());
        addSymbol("res", new Res());

        // Instructions
        addSymbol("nop", new Nop());
        addSymbol("ror", new Ror());
        addSymbol("rol", new Rol());
        addSymbol("shr", new Shr());
        addSymbol("shl", new Shl());
        addSymbol("rcr", new Rcr());
        addSymbol("rcl", new Rcl());
        addSymbol("sar", new Sar());
        addSymbol("sal", new Sal());
        addSymbol("add", new Add());
        addSymbol("addx", new Addx());
        addSymbol("adds", new Adds());
        addSymbol("addsx", new Addsx());
        addSymbol("sub", new Sub());
        addSymbol("subx", new Subx());
        addSymbol("subs", new Subs());
        addSymbol("subsx", new Subsx());
        addSymbol("cmp", new Cmp());
        addSymbol("cmpx", new Cmpx());
        addSymbol("cmps", new Cmps());
        addSymbol("cmpsx", new Cmpsx());
        addSymbol("cmpr", new Cmpr());
        addSymbol("cmpm", new Cmpm());
        addSymbol("subr", new Subr());
        addSymbol("cmpsub", new Cmpsub());
        addSymbol("fge", new Fge());
        addSymbol("fle", new Fle());
        addSymbol("fges", new Fges());
        addSymbol("fles", new Fles());
        addSymbol("sumc", new Sumc());
        addSymbol("sumnc", new Sumnc());
        addSymbol("sumz", new Sumz());
        addSymbol("sumnz", new Sumnz());
        addSymbol("testb", new Testb());
        addSymbol("testbn", new Testbn());
        addSymbol("bitl", new Bitl());
        addSymbol("bith", new Bith());
        addSymbol("bitc", new Bitc());
        addSymbol("bitnc", new Bitnc());
        addSymbol("bitz", new Bitz());
        addSymbol("bitnz", new Bitnz());
        addSymbol("bitrnd", new Bitrnd());
        addSymbol("bitnot", new Bitnot());
        addSymbol("and", new And());
        addSymbol("andn", new Andn());
        addSymbol("or", new Or());
        addSymbol("xor", new Xor());
        addSymbol("muxc", new Muxc());
        addSymbol("muxnc", new Muxnc());
        addSymbol("muxz", new Muxz());
        addSymbol("muxnz", new Muxnz());
        addSymbol("mov", new Mov());
        addSymbol("not", new Not());
        addSymbol("abs", new Abs());
        addSymbol("neg", new Neg());
        addSymbol("negc", new Negc());
        addSymbol("negnc", new Negnc());
        addSymbol("negz", new Negz());
        addSymbol("negnz", new Negnz());
        addSymbol("incmod", new Incmod());
        addSymbol("decmod", new Decmod());
        addSymbol("zerox", new Zerox());
        addSymbol("signx", new Signx());
        addSymbol("encod", new Encod());
        addSymbol("ones", new Ones());
        addSymbol("test", new Test());
        addSymbol("testn", new Testn());
        addSymbol("setnib", new Setnib());
        addSymbol("getnib", new Getnib());
        addSymbol("rolnib", new Rolnib());
        addSymbol("setbyte", new Setbyte());
        addSymbol("getbyte", new Getbyte());
        addSymbol("rolbyte", new Rolbyte());
        addSymbol("setword", new Setword());
        addSymbol("getword", new Getword());
        addSymbol("rolword", new Rolword());
        addSymbol("altsn", new Altsn());
        addSymbol("altgn", new Altgn());
        addSymbol("altsb", new Altsb());
        addSymbol("altgb", new Altgb());
        addSymbol("altsw", new Altsw());
        addSymbol("altgw", new Altgw());
        addSymbol("altr", new Altr());
        addSymbol("altd", new Altd());
        addSymbol("alts", new Alts());
        addSymbol("altb", new Altb());
        addSymbol("alti", new Alti());
        addSymbol("setr", new Setr());
        addSymbol("setd", new Setd());
        addSymbol("sets", new Sets());
        addSymbol("decod", new Decod());
        addSymbol("bmask", new Bmask());
        addSymbol("crcbit", new Crcbit());
        addSymbol("crcnib", new Crcnib());
        addSymbol("muxnits", new Muxnits());
        addSymbol("muxnibs", new Muxnibs());
        addSymbol("muxq", new Muxq());
        addSymbol("movbyts", new Movbyts());
        addSymbol("mul", new Mul());
        addSymbol("muls", new Muls());
        addSymbol("sca", new Sca());
        addSymbol("scas", new Scas());
        addSymbol("addpix", new Addpix());
        addSymbol("mulpix", new Mulpix());
        addSymbol("blnpix", new Blnpix());
        addSymbol("mixpix", new Mixpix());
        addSymbol("addct1", new Addct1());
        addSymbol("addct2", new Addct2());
        addSymbol("addct3", new Addct3());
        addSymbol("wmlong", new Wmlong());
        addSymbol("rqpin", new Rqpin());
        addSymbol("rdpin", new Rdpin());
        addSymbol("rdlut", new Rdlut());
        addSymbol("rdbyte", new Rdbyte());
        addSymbol("rdword", new Rdword());
        addSymbol("rdlong", new Rdlong());
        addSymbol("popa", new Popa());
        addSymbol("popb", new Popb());
        addSymbol("calld", new Calld());
        addSymbol("resi3", new Resi3());
        addSymbol("resi2", new Resi2());
        addSymbol("resi1", new Resi1());
        addSymbol("resi0", new Resi0());
        addSymbol("reti3", new Reti3());
        addSymbol("reti2", new Reti2());
        addSymbol("reti1", new Reti1());
        addSymbol("reti0", new Reti0());
        addSymbol("callpa", new Callpa());
        addSymbol("callpb", new Callpb());
        addSymbol("djz", new Djz());
        addSymbol("djnz", new Djnz());
        addSymbol("djf", new Djf());
        addSymbol("djnf", new Djnf());
        addSymbol("ijz", new Ijz());
        addSymbol("ijnz", new Ijnz());
        addSymbol("tjz", new Tjz());
        addSymbol("tjnz", new Tjnz());
        addSymbol("tjf", new Tjf());
        addSymbol("tjnf", new Tjnf());
        addSymbol("tjs", new Tjs());
        addSymbol("tjns", new Tjns());
        addSymbol("tjv", new Tjv());
        addSymbol("jint", new Jint());
        addSymbol("jct1", new Jct1());
        addSymbol("jct2", new Jct2());
        addSymbol("jct3", new Jct3());
        addSymbol("jse1", new Jse1());
        addSymbol("jse2", new Jse2());
        addSymbol("jse3", new Jse3());
        addSymbol("jse4", new Jse4());
        addSymbol("jpat", new Jpat());
        addSymbol("jfbw", new Jfbw());
        addSymbol("jxmt", new Jxmt());
        addSymbol("jxfi", new Jxfi());
        addSymbol("jxro", new Jxro());
        addSymbol("jxrl", new Jxrl());
        addSymbol("jatn", new Jatn());
        addSymbol("jqmt", new Jqmt());
        addSymbol("jnint", new Jnint());
        addSymbol("jnct1", new Jnct1());
        addSymbol("jnct2", new Jnct2());
        addSymbol("jnct3", new Jnct3());
        addSymbol("jnse1", new Jnse1());
        addSymbol("jnse2", new Jnse2());
        addSymbol("jnse3", new Jnse3());
        addSymbol("jnse4", new Jnse4());
        addSymbol("jnpat", new Jnpat());
        addSymbol("jnfbw", new Jnfbw());
        addSymbol("jnxmt", new Jnxmt());
        addSymbol("jnxfi", new Jnxfi());
        addSymbol("jnxro", new Jnxro());
        addSymbol("jnxrl", new Jnxrl());
        addSymbol("jnatn", new Jnatn());
        addSymbol("jnqmt", new Jnqmt());
        addSymbol("setpat", new Setpat());
        addSymbol("akpin", new Akpin());
        addSymbol("wrpin", new Wrpin());
        addSymbol("wxpin", new Wxpin());
        addSymbol("wypin", new Wypin());
        addSymbol("wrlut", new Wrlut());
        addSymbol("wrbyte", new Wrbyte());
        addSymbol("wrword", new Wrword());
        addSymbol("wrlong", new Wrlong());
        addSymbol("pusha", new Pusha());
        addSymbol("pushb", new Pushb());
        addSymbol("rdfast", new Rdfast());
        addSymbol("wrfast", new Wrfast());
        addSymbol("fblock", new Fblock());
        addSymbol("xinit", new Xinit());
        addSymbol("xstop", new Xstop());
        addSymbol("xzero", new Xzero());
        addSymbol("xcont", new Xcont());
        addSymbol("rep", new Rep());
        addSymbol("coginit", new Coginit());
        addSymbol("qmul", new Qmul());
        addSymbol("qdiv", new Qdiv());
        addSymbol("qfrac", new Qfrac());
        addSymbol("qsqrt", new Qsqrt());
        addSymbol("qrotate", new Qrotate());
        addSymbol("qvector", new Qvector());
        addSymbol("hubset", new Hubset());
        addSymbol("cogid", new Cogid());
        addSymbol("cogstop", new Cogstop());
        addSymbol("locknew", new Locknew());
        addSymbol("lockret", new Lockret());
        addSymbol("locktry", new Locktry());
        addSymbol("lockrel", new Lockrel());
        addSymbol("qlog", new Qlog());
        addSymbol("qexp", new Qexp());
        addSymbol("rfbyte", new Rfbyte());
        addSymbol("rfword", new Rfword());
        addSymbol("rflong", new Rflong());
        addSymbol("rfvar", new Rfvar());
        addSymbol("rfvars", new Rfvars());
        addSymbol("wfbyte", new Wfbyte());
        addSymbol("wfword", new Wfword());
        addSymbol("wflong", new Wflong());
        addSymbol("getqx", new Getqx());
        addSymbol("getqy", new Getqy());
        addSymbol("getct", new Getct());
        addSymbol("getrnd", new Getrnd());
        addSymbol("setdacs", new Setdacs());
        addSymbol("setxfrq", new Setxfrq());
        addSymbol("getxacc", new Getxacc());
        addSymbol("waitx", new Waitx());
        addSymbol("setse1", new Setse1());
        addSymbol("setse2", new Setse2());
        addSymbol("setse3", new Setse3());
        addSymbol("setse4", new Setse4());
        addSymbol("pollint", new Pollint());
        addSymbol("pollct1", new Pollct1());
        addSymbol("pollct2", new Pollct2());
        addSymbol("pollct3", new Pollct3());
        addSymbol("pollse1", new Pollse1());
        addSymbol("pollse2", new Pollse2());
        addSymbol("pollse3", new Pollse3());
        addSymbol("pollse4", new Pollse4());
        addSymbol("pollpat", new Pollpat());
        addSymbol("pollfbw", new Pollfbw());
        addSymbol("pollxmt", new Pollxmt());
        addSymbol("pollxfi", new Pollxfi());
        addSymbol("pollxro", new Pollxro());
        addSymbol("pollxrl", new Pollxrl());
        addSymbol("pollatn", new Pollatn());
        addSymbol("pollqmt", new Pollqmt());
        addSymbol("waitint", new Waitint());
        addSymbol("waitct1", new Waitct1());
        addSymbol("waitct2", new Waitct2());
        addSymbol("waitct3", new Waitct3());
        addSymbol("waitse1", new Waitse1());
        addSymbol("waitse2", new Waitse2());
        addSymbol("waitse3", new Waitse3());
        addSymbol("waitse4", new Waitse4());
        addSymbol("waitpat", new Waitpat());
        addSymbol("waitfbw", new Waitfbw());
        addSymbol("waitxmt", new Waitxmt());
        addSymbol("waitxfi", new Waitxfi());
        addSymbol("waitxro", new Waitxro());
        addSymbol("waitxrl", new Waitxrl());
        addSymbol("waitatn", new Waitatn());
        addSymbol("allowi", new Allowi());
        addSymbol("stalli", new Stalli());
        addSymbol("trgint1", new Trgint1());
        addSymbol("trgint2", new Trgint2());
        addSymbol("trgint3", new Trgint3());
        addSymbol("nixint1", new Nixint1());
        addSymbol("nixint2", new Nixint2());
        addSymbol("nixint3", new Nixint3());
        addSymbol("setint1", new Setint1());
        addSymbol("setint2", new Setint2());
        addSymbol("setint3", new Setint3());
        addSymbol("setq", new Setq());
        addSymbol("setq2", new Setq2());
        addSymbol("push", new Push());
        addSymbol("pop", new Pop());
        addSymbol("jmp", new Jmp());
        addSymbol("call", new Call());
        addSymbol("ret", new Ret());
        addSymbol("calla", new Calla());
        addSymbol("reta", new Reta());
        addSymbol("callb", new Callb());
        addSymbol("retb", new Retb());
        addSymbol("jmprel", new Jmprel());
        addSymbol("skip", new Skip());
        addSymbol("skipf", new Skipf());
        addSymbol("execf", new Execf());
        addSymbol("getptr", new Getptr());
        addSymbol("getbrk", new Getbrk());
        addSymbol("cogbrk", new Cogbrk());
        addSymbol("brk", new Brk());
        addSymbol("setluts", new Setluts());
        addSymbol("setcy", new Setcy());
        addSymbol("setci", new Setci());
        addSymbol("setcq", new Setcq());
        addSymbol("setcfrq", new Setcfrq());
        addSymbol("setcmod", new Setcmod());
        addSymbol("setpiv", new Setpiv());
        addSymbol("setpix", new Setpix());
        addSymbol("cogatn", new Cogatn());
        addSymbol("testp", new Testp());
        addSymbol("testpn", new Testpn());
        addSymbol("dirl", new Dirl());
        addSymbol("dirh", new Dirh());
        addSymbol("dirc", new Dirc());
        addSymbol("dirnc", new Dirnc());
        addSymbol("dirz", new Dirz());
        addSymbol("dirnz", new Dirnz());
        addSymbol("dirrnd", new Dirrnd());
        addSymbol("dirnot", new Dirnot());
        addSymbol("outl", new Outl());
        addSymbol("outh", new Outh());
        addSymbol("outc", new Outc());
        addSymbol("outnc", new Outnc());
        addSymbol("outz", new Outz());
        addSymbol("outnz", new Outnz());
        addSymbol("outrnd", new Outrnd());
        addSymbol("outnot", new Outnot());
        addSymbol("fltl", new Fltl());
        addSymbol("flth", new Flth());
        addSymbol("fltc", new Fltc());
        addSymbol("fltnc", new Fltnc());
        addSymbol("fltz", new Fltz());
        addSymbol("fltnz", new Fltnz());
        addSymbol("fltrnd", new Fltrnd());
        addSymbol("fltnot", new Fltnot());
        addSymbol("drvl", new Drvl());
        addSymbol("drvh", new Drvh());
        addSymbol("drvc", new Drvc());
        addSymbol("drvnc", new Drvnc());
        addSymbol("drvz", new Drvz());
        addSymbol("drvnz", new Drvnz());
        addSymbol("drvrnd", new Drvrnd());
        addSymbol("drvnot", new Drvnot());
        addSymbol("splitb", new Splitb());
        addSymbol("mergeb", new Mergeb());
        addSymbol("splitw", new Splitw());
        addSymbol("mergew", new Mergew());
        addSymbol("seussf", new Seussf());
        addSymbol("seussr", new Seussr());
        addSymbol("rgbsqz", new Rgbsqz());
        addSymbol("rgbexp", new Rgbexp());
        addSymbol("xoro32", new Xoro32());
        addSymbol("rev", new Rev());
        addSymbol("rczr", new Rczr());
        addSymbol("rczl", new Rczl());
        addSymbol("wrc", new Wrc());
        addSymbol("wrnc", new Wrnc());
        addSymbol("wrz", new Wrz());
        addSymbol("wrnz", new Wrnz());
        addSymbol("modcz", new Modcz());
        addSymbol("modc", new Modc());
        addSymbol("modz", new Modz());
        addSymbol("setscp", new Setscp());
        addSymbol("getscp", new Getscp());
        addSymbol("loc", new Loc());
        addSymbol("augs", new Augs());
        addSymbol("augd", new Augd());

        // Registers
        addSymbol("ijmp3", new NumberLiteral(0x1F0));
        addSymbol("iret3", new NumberLiteral(0x1F1));
        addSymbol("ijmp2", new NumberLiteral(0x1F2));
        addSymbol("iret2", new NumberLiteral(0x1F3));
        addSymbol("ijmp1", new NumberLiteral(0x1F4));
        addSymbol("iret1", new NumberLiteral(0x1F5));
        addSymbol("pa", new NumberLiteral(0x1F6));
        addSymbol("pb", new NumberLiteral(0x1F7));
        addSymbol("ptra", new NumberLiteral(0x1F8));
        addSymbol("ptrb", new NumberLiteral(0x1F9));
        addSymbol("dira", new NumberLiteral(0x1FA));
        addSymbol("dirb", new NumberLiteral(0x1FB));
        addSymbol("outa", new NumberLiteral(0x1FC));
        addSymbol("outb", new NumberLiteral(0x1FD));
        addSymbol("ina", new NumberLiteral(0x1FE));
        addSymbol("inb", new NumberLiteral(0x1FF));

        // Conditions
        addSymbol("_ret_", 0b0000);
        addSymbol("if_nc_and_nz", 0b0001);
        addSymbol("if_nz_and_nc", 0b0001);
        addSymbol("if_gt", 0b0001);
        addSymbol("if_a", 0b0001);
        addSymbol("if_00", 0b0001);
        addSymbol("if_nc_and_z", 0b0010);
        addSymbol("if_z_and_nc", 0b0010);
        addSymbol("if_01", 0b0010);
        addSymbol("if_nc", 0b0011);
        addSymbol("if_ge", 0b0011);
        addSymbol("if_ae", 0b0011);
        addSymbol("if_0x", 0b0011);
        addSymbol("if_c_and_nz", 0b0100);
        addSymbol("if_nz_and_c", 0b0100);
        addSymbol("if_10", 0b0100);
        addSymbol("if_nz", 0b0101);
        addSymbol("if_ne", 0b0101);
        addSymbol("if_x0", 0b0101);
        addSymbol("if_c_ne_z", 0b0110);
        addSymbol("if_z_ne_c", 0b0110);
        addSymbol("if_diff", 0b0110);
        addSymbol("if_nc_or_nz", 0b0111);
        addSymbol("if_nz_or_nc", 0b0111);
        addSymbol("if_not_11", 0b0111);
        addSymbol("if_c_and_z", 0b1000);
        addSymbol("if_z_and_c", 0b1000);
        addSymbol("if_11", 0b1000);
        addSymbol("if_c_eq_z", 0b1001);
        addSymbol("if_z_eq_c", 0b1001);
        addSymbol("if_same", 0b1001);
        addSymbol("if_z", 0b1010);
        addSymbol("if_e", 0b1010);
        addSymbol("if_x1", 0b1010);
        addSymbol("if_nc_or_z", 0b1011);
        addSymbol("if_z_or_nc", 0b1011);
        addSymbol("if_not_10", 0b1011);
        addSymbol("if_c", 0b1100);
        addSymbol("if_lt", 0b1100);
        addSymbol("if_b", 0b1100);
        addSymbol("if_1x", 0b1100);
        addSymbol("if_c_or_nz", 0b1101);
        addSymbol("if_nz_or_c", 0b1101);
        addSymbol("if_not_01", 0b1101);
        addSymbol("if_c_or_z", 0b1110);
        addSymbol("if_z_or_c", 0b1110);
        addSymbol("if_le", 0b1110);
        addSymbol("if_be", 0b1110);
        addSymbol("if_not_00", 0b1110);

        // Modc
        addSymbol("_clr", 0b0000);
        addSymbol("_nc_and_nz", 0b0001);
        addSymbol("_nz_and_nc", 0b0001);
        addSymbol("_gt", 0b0001);
        addSymbol("_a", 0b0001);
        addSymbol("_00", 0b0001);
        addSymbol("_nc_and_z", 0b0010);
        addSymbol("_z_and_nc", 0b0010);
        addSymbol("_01", 0b0010);
        addSymbol("_nc", 0b0011);
        addSymbol("_ge", 0b0011);
        addSymbol("_ae", 0b0011);
        addSymbol("_0x", 0b0011);
        addSymbol("_c_and_nz", 0b0100);
        addSymbol("_nz_and_c", 0b0100);
        addSymbol("_10", 0b0100);
        addSymbol("_nz", 0b0101);
        addSymbol("_ne", 0b0101);
        addSymbol("_x0", 0b0101);
        addSymbol("_c_ne_z", 0b0110);
        addSymbol("_z_ne_c", 0b0110);
        addSymbol("_diff", 0b0110);
        addSymbol("_nc_or_nz", 0b0111);
        addSymbol("_nz_or_nc", 0b0111);
        addSymbol("_not_11", 0b0111);
        addSymbol("_c_and_z", 0b1000);
        addSymbol("_z_and_c", 0b1000);
        addSymbol("_11", 0b1000);
        addSymbol("_c_eq_z", 0b1001);
        addSymbol("_z_eq_c", 0b1001);
        addSymbol("_same", 0b1001);
        addSymbol("_z", 0b1010);
        addSymbol("_e", 0b1010);
        addSymbol("_x1", 0b1010);
        addSymbol("_nc_or_z", 0b1011);
        addSymbol("_z_or_nc", 0b1011);
        addSymbol("_not_10", 0b1011);
        addSymbol("_c", 0b1100);
        addSymbol("_lt", 0b1100);
        addSymbol("_b", 0b1100);
        addSymbol("_1x", 0b1100);
        addSymbol("_c_or_nz", 0b1101);
        addSymbol("_nz_or_c", 0b1101);
        addSymbol("_not_01", 0b1101);
        addSymbol("_c_or_z", 0b1110);
        addSymbol("_z_or_c", 0b1110);
        addSymbol("_le", 0b1110);
        addSymbol("_be", 0b1110);
        addSymbol("_not_00", 0b1110);
    }

    void addSymbol(String name, int value) {
        symbols.put(name.toLowerCase(), new NumberLiteral(value));
    }

}
